using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CeremonyBazar.Entity
{
    public class BaseEntity
    {
        [Key]// -- this specify that this coloumn automatically generated by the database (Identity Column)
        public int Id { get; set; }

    }
}